apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  AUTH_SVC_URL: "http://auth-svc:8081"
  DATA_SVC_URL: "http://data-svc:8082"
  ML_SVC_URL: "http://65.109.169.137:8000"
  SESSION_EXPIRY: "168h"
  COOKIE_DOMAIN: "diabrisk.local"
  COOKIE_SECURE: "false"
